# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://PininQ.github.io/
date_format: "ordinal"
title: "小花椒"
subtitle: "三旬尚远浓烟散，一如年少迟夏归。"
description: "覃斌的个人博客"
keywords: 小花椒, Bin Qin, qblogin, qinbin
timezone: Asia/Guangzhou
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Bin Qin
organization: "小花椒视频网站"
organization_url: https://www.xhuajiao.top
github_username: PininQ
location: Guangzhou, China
email: 2538323140@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: PininQ/PininQ.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username:
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: PininQ
    repo: blog-comments
    oauth:
        client_id: 92ff8597339ab1695095
        client_secret: dceeff258a89f54f4ed3a10c828872ab2ebd2507
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: PininQ
    repo: blog-comments
    clientID: 92ff8597339ab1695095
    clientSecret: dceeff258a89f54f4ed3a10c828872ab2ebd2507
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
